//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class testTable
    {
        public int Id { get; set; }
        public string login1 { get; set; }
        public string password1 { get; set; }
        public Nullable<int> roleid { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
